### ISSUE TITLE
有个疑问？

### ISSUE THREAD

**Issue by jennazheng90** [fengbingchun/PyTorch_Test#1]
您好，在执行您的测试脚本时，报了个错？
![image](https://user-images.githubusercontent.com/32327387/57189631-4d301700-6f43-11e9-92d0-7759165d69a2.png)

 这是什么问题呢？？

**Comment by fengbingchun** [comment]
@jennazheng90  第一次运行脚本时需要下载一个faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth二进制文件，此文件有167.3MB，可以验证下此文件是否已经完整下载完成？

**Comment by jennazheng90** [comment]
> @jennazheng90 第一次运行脚本时需要下载一个faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth二进制文件，此文件有167.3MB，可以验证下此文件是否已经完整下载完成？

已经下载，并放到文件夹了~

**Comment by jennazheng90** [comment]
已经好啦 谢谢您！赞
